config/routes.rb
Unbound::Application.routes.draw do

  resources :pages_articles

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end

  
  resources :homes

  resources :jobs

  resources :users

  resources :states

  resources :countries

  resources :continents

  resources :pages

  resources :issues

  resources :journals

  resources :categories

  resources :articles

  

  root :to => 'homes#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :category_id, :content, :cover, :is_deleted, :is_draft, :slug, :title, :user_id, :featured, :superfeatured, :size

  mount_uploader :cover, CoverUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category
  belongs_to :user

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :name, :slug


  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :articles
  has_many :journals
  
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  attr_accessible :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :countries

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :continent_id, :flag, :name, :slug


  extend FriendlyId
  friendly_id :name, use: :slugged


  belongs_to :continent

  has_many :states
  

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :couverture, :edition, :journal_id, :special, :version

  mount_uploader :couverture, CouvertureUploader

  belongs_to :journal

  has_many :pages
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :description, :name


  belongs_to :user
  
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  attr_accessible :affiche, :continent_id, :country_id, :description, :state_id, :title, :user_id

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :affiche, AfficheUploader

  belongs_to :user
  belongs_to :country
  belongs_to :continent
  belongs_to :state_id

  has_many :issues

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :background, :issue_id, :name, :order, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :issue


end

app/models/pages_article.rb
class PagesArticle < ActiveRecord::Base
  attr_accessible :article_id, :page_id
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug

  belongs_to :country
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :country_id, :job_id, :slug, :state_id, :username

  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :articles
  has_many :journals

  belongs_to :country
  belongs_to :state

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>

  <div class="field">
    <%= f.label :version %><br />
    <%= f.number_field :version %>
  </div>

  <div class="field">
    <%= f.label :couverture %><br />
    <%= f.file_field :couverture %>
  </div>

  <div class="field">
    <%= f.label :special %><br />
    <%= f.text_area :special %>
  </div>

  <div class="field">
    <%= f.label :journal_id %><br />
    <select id="issue_journal_id" name="issue[journal_id]">
      <% Journal.where("user_id = ?", current_user.id).order("title ASC").each do |journal|  %>
        <option value="<%= journal.id %>"><%= journal.title %> </option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <%= f.label :edition %><br />
    <%= f.text_field :edition %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table>
  <tr>
    <th>Version</th>
    <th>Couverture</th>
    <th>Special</th>
    <th>Journal</th>
    <th>Edition</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.version %></td>
    <td><%= issue.couverture %></td>
    <td><%= issue.special %></td>
    <td><%= issue.journal_id %></td>
    <td><%= issue.edition %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Version:</b>
  <%= @issue.version %>
</p>

<p>
  <b>Couverture:</b>
  <%= @issue.couverture %>
</p>

<p>
  <b>Special:</b>
  <%= @issue.special %>
</p>

<p>
  <b>Journal:</b>
  <%= @issue.journal_id %>
</p>

<p>
  <b>Edition:</b>
  <%= @issue.edition %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>