config/routes.rb
Unbound::Application.routes.draw do

  resources :pages_articles

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end

  
  resources :homes

  resources :jobs

  resources :users

  resources :states

  resources :countries

  resources :continents

  resources :pages

  resources :issues

  resources :journals

  resources :categories

  resources :articles

  

  root :to => 'homes#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :category_id, :content, :cover, :is_deleted, :is_draft, :slug, :title, :user_id, :featured, :superfeatured, :size

  mount_uploader :cover, CoverUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category
  belongs_to :user

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :name, :slug


  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :articles
  has_many :journals
  
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  attr_accessible :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :countries

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :continent_id, :flag, :name, :slug


  extend FriendlyId
  friendly_id :name, use: :slugged


  belongs_to :continent

  has_many :states
  

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :couverture, :edition, :journal_id, :special, :version

  mount_uploader :couverture, CouvertureUploader

  belongs_to :journal

  has_many :pages
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :description, :name


  belongs_to :user
  
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  attr_accessible :affiche, :continent_id, :country_id, :description, :state_id, :title, :user_id

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :affiche, AfficheUploader

  belongs_to :user
  belongs_to :country
  belongs_to :continent
  belongs_to :state_id

  has_many :issues

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :background, :issue_id, :name, :order, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :issue


end

app/models/pages_article.rb
class PagesArticle < ActiveRecord::Base
  attr_accessible :article_id, :page_id
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug

  belongs_to :country
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :country_id, :job_id, :slug, :state_id, :username

  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :articles
  has_many :journals

  belongs_to :country
  belongs_to :state

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    @journal = Journal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/new
  # GET /journals/new.json
  def new
    @journal = Journal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/1/edit
  def edit
    @journal = Journal.find(params[:id])
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(params[:journal])

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render json: @journal, status: :created, location: @journal }
      else
        format.html { render action: "new" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /journals/1
  # PUT /journals/1.json
  def update
    @journal = Journal.find(params[:id])

    respond_to do |format|
      if @journal.update_attributes(params[:journal])
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal = Journal.find(params[:id])
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :affiche %><br />
    <%= f.file_field :affiche %>
  </div>

    <% if user_signed_in? %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <% end %>

  <div class="field">
    <%= f.label :country_id %><br />
    <select id="journal_country_id" name="journal[country_id]">
      <% Country.order("name ASC").each do |country|  %>
        <option value="<%= country.id %>"><%= country.name %> </option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <%= f.label :state_id %><br />
    <select id="journal_state_id" name="journal[state_id]">
      <% State.order("name ASC").each do |state|  %>
        <option value="<%= state.id %>"><%= state.name %> </option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :continent_id %><br />
    <select id="journal_continent_id" name="journal[continent_id]">
      <% Continent.order("name ASC").each do |continent|  %>
        <option value="<%= continent.id %>"><%= continent.name %> </option>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<h1>Listing journals</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Affiche</th>
    <th>User</th>
    <th>Country</th>
    <th>State</th>
    <th>Continent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @journals.each do |journal| %>
  <tr>
    <td><%= journal.title %></td>
    <td><%= journal.description %></td>
    <td><%= journal.affiche %></td>
    <td><%= journal.user_id %></td>
    <td><%= journal.country_id %></td>
    <td><%= journal.state_id %></td>
    <td><%= journal.continent_id %></td>
    <td><%= link_to 'Show', journal %></td>
    <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
    <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Journal', new_journal_path %>

app/views/journals/new.html.erb
<h1>New journal</h1>

<%= render 'form' %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @journal.title %>
</p>

<p>
  <b>Description:</b>
  <%= @journal.description %>
</p>

<p>
  <b>Affiche:</b>
  <%= image_tag @journal.affiche_url.to_s %>
</p>

<p>
  <b>User:</b>
  <%= @journal.user_id %>
</p>

<p>
  <b>Country:</b>
  <%= @journal.country_id %>
</p>

<p>
  <b>State:</b>
  <%= @journal.state_id %>
</p>

<p>
  <b>Continent:</b>
  <%= @journal.continent_id %>
</p>


<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>